#%RAML 1.0
title: plan-sponsor-rs-v1
baseUri: http://plan-sponsor-rs-v1/{v1}
version: 1.0

/contact-search:
  get:
    queryParameters: 
      
  post:
/uup-search:
/clients/{client-id}:
/contact-history-search:
/contact-number-generator:
/retrieve-notice-count:
/role-search:
/pre-load-contact:
/retrieve-plan-info:
/service-requests:
/bookorder-plan-search:
/customers/{customer-number}:
/rca-plan-data-search:
/submit-vendor-payment:
/add-vendor:
/plan-service-credit:
/custom-standard-reports:
/employers/{ein}:
/retrieve-intermediary-history:
/plan-group:
/plan-deaggregation:
/excess-revenue-deposit:
/send-notifications:
/ping: